### ISSUE TITLE
Pythia main03.cc for normailzing number

### ISSUE THREAD

**Issue by PanLing1994** [cms-externals/pythia8#15]
// Final statistics. Normalize and output histograms.
  pythia.stat();
  dndy   *=  5. / nEvent;
  dndeta *=  5. / nEvent;
  dndpT  *= 10. / nEvent;
  cout << pThard << nFinal << nCharged << dndy << dndeta << dndpT << epCons;
######################################################
How you normalize this histograms? I don't understand the number("5"/"10") meaning, It is a unit transformation?

**Comment by Dr15Jones** [comment]
assign generators

**Comment by qliphy** [comment]
@PanLing1994   The factors are defined by 1/(bin size), i.e. 1/[ (Bin Range)/(Number of Bins)]
https://github.com/cms-externals/pythia8/blob/master/examples/main03.cc#L36-L38

**Comment by smrenna** [comment]
dndy has 100 bins over the range(-10,10).    100/20 = 5
dndeta also has 100 bins over the range (-10,10)
dndpT has 100 bins over a range of 10 GeV, 100/10 = 10.

This transformation is removing the bin width dependence.
If someone made the same distribution, but with a different bin width, the histograms can be directly compared.
